# SPDX-License-Identifier: Apache-2.0

services:
  vllm-service:
    image: vllm-xpu-env:latest
    container_name: xpu-vllm-service
    devices:
      - /dev/dri:/dev/dri
    ports:
      - "8000:8000"
    volumes:
      - "${HOME}/.cache/huggingface:/root/.cache/huggingface"
      - "/dev/dri/by-path:/dev/dri/by-path"
    shm_size: 1g
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      HF_TOKEN: ${HF_TOKEN}
      LLM_MODEL_ID: Qwen/Qwen2.5
      HF_OFFLINE: 1
      TRANSFORMERS_OFFLINE: 1
      VLLM_TORCH_PROFILER_DIR: "/mnt"
      VLLM_USE_XFORMERS: 0
      LLM_ENDPOINT_PORT: ${LLM_ENDPOINT_PORT}
      VLLM_SKIP_WARMUP: ${VLLM_SKIP_WARMUP:-false}
      CUDA_LAUNCH_BLOCKING: 1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://${ip_address}:${LLM_ENDPOINT_PORT}/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 100
    #command: --model "Qwen/Qwen3-4B" --host 0.0.0.0 --port 8000
    command: --model "Qwen/Qwen3-4B" --host 0.0.0.0 --port ${LLM_ENDPOINT_PORT} --enable-auto-tool-choice --tool-call-parser hermes
    ipc: host
    restart: always
    #network_mode: host

networks:
  default:
    driver: bridge
